name: Gradle Publish

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Publish to repository
      run: ./gradlew publish
      env:
        ORG_GRADLE_PROJECT_mavenUsername: ${{ secrets.REPOSITORY_USERNAME }}
        ORG_GRADLE_PROJECT_mavenAccessToken: ${{ secrets.REPOSITORY_TOKEN }}
